variable "VPC_PRIVATEIP_CIDR" {}
variable "VPC_PUBLICIP_CIDR" {}
variable "ENV" {}
variable "PRIVATE_SUBNET_CIDR" {}
variable "PUBLIC_SUBNET_CIDR" {}
variable "VPC_SUBNET_AZ" {}
variable "DEFAULT_VPC_ID" {}
variable "DEFAULT_VPC_CIDR" {}
variable "INTERNAL_DNS_ZONE_ID" {}